apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot  # Update this
  template:
    metadata:
      labels:
        app: springboot  # Update this
    spec:
      containers:
        - name: springboot
          image: priyushinde/app:latest
          ports:
            - containerPort: 8080